using BarberReservation.Application.Reservation.Validation;
namespace BarberReservation.Application.Reservation.Queries.Admin.GetAllAdminReservations;

public sealed class GetAllAdminReservationsQueryValidator : ReservationListQueryValidatorBase<GetAllAdminReservationsQuery> { }
