using BarberReservation.Application.Reservation.Validation;

namespace BarberReservation.Application.Reservation.Commands.Hairdresser.CreateHairDresserReservation;

public sealed class CreateHairdresserReservationCommandValidator : ReservationCreateValidatorBase<CreateHairDresserReservationCommand> { }
