using BarberReservation.Application.Common.Validation.IdValidation;

namespace BarberReservation.Application.HairdresserService.Commands.Self.DeactivateSelfHairdresserService;

public sealed class DeactivateSelfHairdresserServiceCommandValidator : IdValidator<DeactivateSelfHairdresserServiceCommand> { }
